mode:
  develop: true

db:
  dsn: root:123321@tcp(127.0.0.1:3306)/test?charset=utf8mb4&parseTime=True&loc=Local
  maxIdleConns: 10 #最多空闲连接数
  maxOpenConns: 10 #最多打开连接数

redis:
  url: localhost:6379

server:
  port: :8080

jwt:
  tokenExpire: 30 #token时长
  signingKey: nftcard

nft:
  initasset: 20 #初始资金
  mintcost: 5  #铸造资金
  minetime: 7 #挖矿冷却期，单位小时

log:
  maxSize: 1 #最大尺寸（MB）
  maxBackups: 10 #保留旧文件最大个数
  maxAge: 90 #保留旧文件最大天数 